name: Pipeline-PRD

on:
  push:
    branches: [ "main" ]

jobs:
  Integration:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -c Release -o ./publish
    - name: Upload Publish Directory as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: publish-artifact
        path: ./publish

  Deploy:

    runs-on: ubuntu-latest
    needs: Integration

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Install Lambda Tools
      run: dotnet tool install -g Amazon.Lambda.Tools
    - name: Download Publish Artifact
      uses: actions/download-artifact@v3
      with:
        name: publish-artifact
        path: ./publish
    - name: Install jq
      run: sudo apt-get install -y jq
    - name: Substitute secrets in appsettings using jq
      env:
        CONNECTION_STRING_PRD: ${{ secrets.CONNECTION_STRING_PRD }}
        ENCRYPTION_KEY_PRD: ${{ secrets.ENCRYPTION_KEY_PRD }}
        JWT_KEY_PRD: ${{ secrets.JWT_KEY_PRD }}
        JWT_ISSUER_PRD: ${{ secrets.JWT_ISSUER_PRD }}
        EMAIL_ACCESS_KEY_PRD: ${{ secrets.EMAIL_ACCESS_KEY_PRD }}
        EMAIL_SECRET_KEY_PRD: ${{ secrets.EMAIL_SECRET_KEY_PRD }}
        AUTH_URL_PRD: ${{ secrets.AUTH_URL_PRD }}
        BUCKET_ACCESS_KEY_PRD: ${{ secrets.BUCKET_ACCESS_KEY_PRD }}
        BUCKET_SECRET_KEY_PRD: ${{ secrets.BUCKET_SECRET_KEY_PRD }}
        BUCKET_NAME_PRD: ${{ secrets.BUCKET_NAME_PRD }}
      run: |
        jq '.MongoDBSettings.ConnectionString = env.CONNECTION_STRING_PRD |
            .EncryptionKey = env.ENCRYPTION_KEY_PRD |
            .Jwt.Key = env.JWT_KEY_PRD |
            .Jwt.Issuer = env.JWT_ISSUER_PRD |
            .EmailSettings.AccessKey = env.EMAIL_ACCESS_KEY_PRD |
            .EmailSettings.SecretKey = env.EMAIL_SECRET_KEY_PRD |
            .APIs.AuthUrl = env.AUTH_URL_PRD |
            .BucketSettings.AccessKey = env.BUCKET_ACCESS_KEY_PRD |
            .BucketSettings.SecretKey = env.BUCKET_SECRET_KEY_PRD |
            .BucketSettings.BucketName = env.BUCKET_NAME_PRD' \
            ./publish/appsettings.Production.json > ./publish/appsettings.Production.tmp.json && \
        mv ./publish/appsettings.Production.tmp.json ./publish/appsettings.Production.json
    - name: Deploy to AWS Lambda
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PRD }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PRD }}
        AWS_REGION: ${{ secrets.AWS_REGION_PRD }}
      run: |
        cd ./publish
        zip -r function.zip .
        aws lambda update-function-code --function-name ${{ secrets.LAMBDA_NAME_PRD }} --zip-file fileb://function.zip
